fail-fast: true

repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [--diff, --check]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        args: [--strict]