name: Code quality checks
on:
    pull_request:
    push:
    
jobs:
    code_quality:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3
            - name: "Install Python"
              uses: actions/setup-python@v4
              with:
                    python-version: '3.11' 
            - name: "Install dependencies"
              run: pip install -r requirements/pipeline_requirements.txt
            - name: "Run ruff"
              run: ruff check .
            - name: "Run mypy"
              run: mypy --strict %(git ls-files '*.py')