name: Code quality checks
on:
    pull_request:
    push:
        branches: 
            - main
    
jobs:
    code_quality:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v3
            - name: "Install Python"
              uses: actions/setup-python@v4
              with:
                    python-version: '3.11' 
            - name: "Install dependencies"
              run: pip install requirements/pipeline_requirements.txt
            - name: "Run black"
              run: black --diff --check $(git ls-files '*.py')
            - name: "Run mypy"
              run: mypy --strict %(git ls-files '*.py')